name: Docker Image CI

on:
  push:
    branches: [ "release" ]
      
jobs:
  
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Build the Docker image
        uses: actions/checkout@v3
        run: docker build . --file Dockerfile --tag registry.digitalocean.com/cctv-vt/pocketbase:latest
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
        
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600
        
      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/cctv-vt/pocketbase:latest
        